import pandas as pd
import os
import string
import re
import html

def load_data(load_path):
    '''
    load_path: path of raw csv file
    '''
    data_df=pd.read_csv(load_path,encoding='utf-8')
    return data_df

def columns_filter(data_df):
    '''
    data_df: raw dataframe from the csv file
    '''
    try:
        data_df1=data_df[['id','createdAt','url','author/userName','lang','text','viewCount','likeCount','replyCount','retweetCount','quoteCount']]
    except:
        data_df1=data_df[['id','createdAt','twitterUrl','author/userName','lang','text','viewCount','likeCount','replyCount','retweetCount','quoteCount']]
    data_df1.columns=['id','timestamp','url','username','lang','text','views','likes','replies','retweets','quotes']
    return data_df1

def lang_filter(data_df1):
    '''
    data_df1: dataframe generated by columns_filter()
    '''
    data_df2=data_df1[data_df1['lang']=='en']
    return data_df2

def duplicate_filter(data_df2):
    '''
    data_df2: dataframe generated by lang_filter()
    '''
    data_df3=data_df2.drop_duplicates(subset=['text','url'],keep='first')
    return data_df3

def clean_text(text):
    '''
    text: text from data_df3
    '''
    if pd.isna(text):
        return None
    puncts=set('''…。！＂＃＄％＆＇（）＊＋，－．／：；＜＝＞？＠［＼］＾＿｀｛｜｝～'''+string.punctuation)
    text=html.unescape(str(text))
    text=re.sub(r'https?://\S+', '',text)
    text=re.sub(r'#\w+','',text)
    text=re.sub(r'@\w+','',text)
    pattern=f'''[^A-Za-z0-9\s{"".join(map(re.escape,puncts))}]'''
    text=re.sub(pattern,'',str(text))
    text=re.sub(r'\s+',' ',text).strip()
    return text if text else None

def content_clean(data_df3):
    '''
    data_df3: dataframe generated by duplicate_filter()
    '''
    data_df_final=data_df3.copy()
    data_df_final['text']=data_df3['text'].apply(clean_text)
    data_df_final=data_df_final.dropna(subset=['text'])
    return data_df_final

def save_data(data_df_final,filename):
    '''
    data_df_final: dataframe generated by content_clean()
    filename: final csv file ("filename.csv")
    '''
    os.makedirs('clean_results',exist_ok=True)
    save_path=fr'''clean_results/{filename}'''
    data_df_final.to_csv(save_path,index=False,encoding='utf-8')
    print(f'''data saved: {save_path}, {data_df_final.shape[0]} rows in total''')

def data_cleaning(load_path,filename):
    '''
    load_path: path of raw csv file
    filename: final csv file ("filename.csv")
    '''
    data_df=load_data(load_path)
    data_df1=columns_filter(data_df)
    data_df2=lang_filter(data_df1)
    data_df3=duplicate_filter(data_df2)
    data_df_final=content_clean(data_df3)
    save_data(data_df_final,filename)
