import pandas as pd
from tqdm import tqdm
from transformers import AutoTokenizer,AutoModelForSequenceClassification
import torch
import os

def load_data(load_path):
    '''
    load_path: path of cleaned csv file
    '''
    data_df=pd.read_csv(load_path,encoding='utf-8')
    return data_df

def sentiment_tagging(data_df,model_name):
    '''
    data_df: dataframe loaded
    model_name: the pretrained sentiment_analysis model
    '''
    text_list=data_df['text'].to_list()
    if model_name=="tabularisai/robust-sentiment-analysis":
        text_list=[text.lower() for text in text_list]
    sentiment_tags=[]
    tokenizer=AutoTokenizer.from_pretrained(model_name)
    model=AutoModelForSequenceClassification.from_pretrained(model_name)
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()
    id2label=model.config.id2label
    for text in tqdm(text_list,total=len(text_list),desc="sentiment tagging..."):
        inputs=tokenizer(text,return_tensors="pt",padding=True,truncation=True,max_length=512)
        inputs={key:value.to(device) for key,value in inputs.items()}
        with torch.no_grad():
            outputs=model(**inputs)
            probs=torch.nn.functional.softmax(outputs.logits,dim=-1)
            pred=torch.argmax(probs,dim=-1).item()
            sentiment_tag=id2label[pred]
        sentiment_tags.append(sentiment_tag)
    data_df['sentiment_tag']=sentiment_tags
    return data_df

def classify_sentiment(data_df):
    '''
    data_df: dataframe from sentiment_tagging()
    '''
    polarized_labels={"Very Positive","Very Negative"}
    data_df['type']=data_df['sentiment_tag'].apply(lambda x: "polarized" if x in polarized_labels else "neutral")
    return data_df

def save_data(data_df,filename):
    '''
    data_df: dataframe generated by classify_sentiment()
    filename: final csv file ("filename.csv")
    '''
    os.makedirs('senti_results',exist_ok=True)
    save_path=fr'''senti_results/{filename}'''
    data_df.to_csv(save_path,index=False,encoding='utf-8')
    data_df_polarized=data_df[data_df['type']=='polarized']
    print(f'''data saved: {save_path}, polarized rows {len(data_df_polarized)}/{len(data_df)}''')

def senti_tagging(load_path,filename,modelname):
    '''
    load_path: path of cleaned csv file
    filename: final csv file ("filename.csv")
    model_name: the pretrained sentiment_analysis model
    '''
    data_df=load_data(load_path)
    data_df1=sentiment_tagging(data_df,modelname)
    data_df2=classify_sentiment(data_df1)
    save_data(data_df2,filename)